version: "3.8"

services:
  
  api: 
    build: .
    ports:
      - 5000:5000
    environment:
      DB_URL: postgresdb://db/motorbikes
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: motorbikes
    ports: 
      - 5432:5432
    volumes:
      - motorbikes:/data/db

volumes:
  motorbikes: 

