version: "3.8"

services:
  
  api: 
    build: .
    ports:
      - 5000:5000
    environment:
      DB_URL: postgresdb://db/motorbike
  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - motorbike:/data/db

volumes:
  motorbike: 

